export const OMNITRIX_STATES = {
    IDLE: 'IDLE',
    SELECTING: 'SELECTING',
    ACTIVE: 'ACTIVE',
    COOLDOWN: 'COOLDOWN',
    // Celestial Override States
    BOOTING: 'BOOTING',
    OVERCHARGE: 'OVERCHARGE',
    LOCKED: 'LOCKED',
    ALIEN_X_DISCOVERY: 'ALIEN_X_DISCOVERY',
    ALIEN_X_AWAKENING: 'ALIEN_X_AWAKENING',
    CELESTIAL_ARBITRATION: 'CELESTIAL_ARBITRATION',
    CELESTIAL_MODE: 'CELESTIAL_MODE',
    REALITY_STABILIZING: 'REALITY_STABILIZING'
};
